<div class="row">
	<div class="col-lg-12" >
		<div class="panel panel-default" id="scroller_organizationlist_266570221142355520">
			<div class="panel-heading stat-scroller-header">
				&nbsp;Расходы "Ремонт дороги"
			</div><!-- /.panel-heading -->
			<!--<div class="panel-body">-->
				<input hidden="" id="page" value="1">
				<input hidden="" id="sort" value="id">
				<input hidden="" id="order" value="DESC">
				<input hidden="" id="page_size" value="100">

				
				<table class="table table-striped table-bordered table-hover table-responsive">
					<thead>
						<tr>
							<td colspan="6">
								<div class="pull-right" role="group" aria-label="...">&nbsp;
									<button type="button" class="btn btn-primary" aria-label="Задать вопрос" name="add" onclick="row_request('scroller_organizationlist_8673307953024789', null);">Задать вопрос</button>
								</div><!-- /.btn-group -->
							</td>
						</tr>
						<!-- строка заголовков -->
						<tr>
							<th style="width:60px;">
								<span onclick="change_sort('scroller_organizationlist_266570221142355520', 'id');"><u>№</u></span>
								<button type="button" class="btn btn-default btn-xs" aria-label="ID" name="id">
									<span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true"></span>
								</button>
							</th>
							<th style="width:20%;">
								<span onclick="change_sort('scroller_organizationlist_266570221142355520', 'name');"><u>Тема</u></span>
							</th>
							<th style="width:30%;">
								<span onclick="change_sort('scroller_organizationlist_266570221142355520', 'name');"><u>Текст обращения</u></span>
							</th>
							<th style="width:30%;">
								<span onclick="change_sort('scroller_organizationlist_266570221142355520', 'name');"><u>Ответ</u></span>
							</th>
							<th  style="width: 100px;">
								<span onclick="change_sort('scroller_organizationlist_266570221142355520', 'amount');"><u>Статус</u></span>
							</th>
							<th>Действия</th>
						</tr>
					</thead>
					<tbody>
						<!-- строка фильтров -->
						<tr>
							<td class="stat-id-td">
								<input type="number" name="filter_id" value="" class="stat-id-input-field inited" style="width:60px;" min="0">
							</td>
							<td class="">
								<input type="text" name="filter_topic" value="" class="inited">
							</td>
							<td class="">
								<input type="text" name="filter_request" value="" class="inited">
							</td>
							<td class="">
								<input type="email" name="filter_response" value="" class="inited">
							</td>
							<td class="">
								<select name="filter_status_id">
									<option value="*" selected="selected"></option>
									<option value="20">Создан</option>
									<option value="21">Обработан</option>
								</select>
							</td>
							<td class="stat-operations-td">
								<button type="button" class="btn btn-xs" aria-label="Применить" name="apply" onclick="apply_filter('scroller_organizationlist_266570221142355520');"><span class="glyphicon glyphicon-filter" aria-hidden="true"></span></button>
								<button type="button" class="btn btn-xs" aria-label="Очистить" name="clear" onclick="clear_filter('scroller_organizationlist_266570221142355520');"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
							</td>
						</tr>
						<tr class="odd gradeX ">
							<td name="id" id="id">232</td>
							<td name="topic" id="topic">Вопрос о расходе</td>
							<td name="question" id="question">Куда реально пошли деньги?</td>
							<td name="answer" id="answer">На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. </td>
							<td name="status" id="status">Создан</td>
							<td>
								<button type="button" class="btn btn-xs" aria-label="Ответить" name="edit" onclick="row_request('scroller_organizationlist_266570221142355520', '2');"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button>
							</td>
						</tr>
						<tr class="odd gradeX success">
							<td name="id" id="id">212</td>
							<td name="topic" id="topic">Обращение в службу поддержки</td>
							<td name="name" id="name">Как восстановить пароль?</td>
							<td name="contacts" id="contacts">На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. На нужное дело пошли. </td>
							<td name="amount" id="amount">Обработан</td>
							<td>
								<button type="button" class="btn btn-xs" aria-label="Ответить" name="edit" onclick="row_request('scroller_organizationlist_266570221142355520', '2');"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button>
							</td>
						</tr>
						<tr class="odd gradeX ">
							<td name="id" id="id">23</td>
							<td name="topic" id="topic">Вопрос о расходе</td>
							<td name="question" id="question">Где можно посмотреть детализацию расходов?</td>
							<td name="answer" id="answer">Нигде</td>
							<td name="status" id="status">Создан</td>
							<td>
								<button type="button" class="btn btn-xs" aria-label="Ответить" name="edit" onclick="row_request('scroller_organizationlist_266570221142355520', '2');"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="panel-footer">
					<!-- записей на странице -->
					<span class="pull-right">Показывать по&nbsp;
						<select name="page_sizes" onchange="change_page_size('scroller_organizationlist_266570221142355520');">
							<option value="30">30</option>
							<option value="50">50</option>
							<option value="100" selected="selected">100</option>
						</select>
					</span>
					<nav>
							<ul class="pagination stat-pager">
								<li class="disabled"><span aria-label="Previous"><span aria-hidden="true">«</span></span></li>
								<!-- выводим номера страниц -->
								<li class="active"><span><span aria-hidden="true">1</span></span></li>
								<li><a href="#" onclick="change_page('scroller_organizationlist_266570221142355520', 2);">2</a></li>
								<li><a href="#" onclick="change_page('scroller_organizationlist_266570221142355520', 3);">3</a></li>
								<li><a href="#" onclick="change_page('scroller_organizationlist_266570221142355520', 4);">4</a></li>
								<li onclick="change_page('scroller_organizationlist_266570221142355520', 1+1);"><a href="#" aria-label="pager_next"><span aria-hidden="true">»</span></a></li>
							</ul>
						</nav>
				</div>
			<!-- /.panel-body -->
		</div>
	</div>
</div>

<script type="text/javascript"><!--

//--></script>