<div class="row"><div class="col-lg-12"><div>&nbsp;</div></div></div>
<div class="row"><div class="col-lg-12"><div>&nbsp;</div></div></div>
<div class="row"><div class="col-lg-12"><div>&nbsp;</div></div></div>
<div class="row">
	<form class="form-horizontal">
		<div class="form-group">
			<label for="regionSelect" class="col-lg-3 control-label"><?php echo $t->_("index_select_region"); ?></label>
			<div class="col-lg-8">
				<select id="regionSelect" class="form-control extended" onchange="onRegionChange(this);">
					<option value="*" selected="selected" label="&nbsp;">&nbsp;</option>
					<?php if(isset($regions)) { 
						foreach($regions as $id => $name) { ?>
							<option value="<?php echo $id; ?>"><?php echo $name; ?></option>
						<?php } ?>
					<?php } ?>
				</select>
				<!--<input type="region" class="form-control" id="inputRegion" placeholder="Регион">-->
			</div>
		</div>
		<div class="form-group">
			<label for="organizationSelect" class="col-lg-3 control-label"><?php echo $t->_("index_select_organization"); ?></label>
			<div class="col-lg-8">
				<select id="organizationSelect" class="form-control extended" onchange="onOrganizationChange(this);">
					<option value="*" selected="selected" label="&nbsp;">&nbsp;</option>
					<?php if(isset($organizations)) { 
						foreach($organizations as $id => $org) { ?>
							<option value="<?php echo $org['id']; ?>"><?php echo $org['name'] . ' (' . $regions[$org['regionID']] . ')'; ?></option>
						<?php } ?>
					<?php } ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<div class="col-lg-offset-3 col-lg-10">
				<button id="showExpensesBtn" type="button" class="btn btn-primary" disabled onclick="onShowExpensesClick();">Перейти</button>
			</div>
		</div>
	</form>
</div>

<script type="text/javascript"><!--

var regions = <?php echo json_encode($regions); ?>;
var organizations = <?php echo json_encode($organizations); ?>;
console.log(organizations);

// код необходим для нормальной работы форм с кнопками "Назад" в браузере
if ('onpageshow' in window) {
    window.addEventListener('pageshow', PageShowHandler, false);
}

function PageShowHandler() {
	var regCtrl = document.getElementById('regionSelect');
	var regionID = regCtrl.value;
	var orgCtrl = document.getElementById('organizationSelect');
	var organizationID = orgCtrl.value;
	if(regionID != "*") {
		onRegionChange(regCtrl);
	}
	if(organizationID != "*") {
		orgCtrl.value = organizationID;
		onOrganizationChange(orgCtrl);
	}
}

function onRegionChange(ctrl) {
	var regionID = ctrl.value;
	var organizationID = document.getElementById('organizationSelect').value;
	var selectOrgs = document.getElementById("organizationSelect");
	selectOrgs.innerHTML = "";
	var optionsHTML;
	if(organizationID == "*") optionsHTML = '<option value="*" selected="selected" label="&nbsp;">&nbsp;</option>';
	else optionsHTML = '<option value="*" label="&nbsp;">&nbsp;</option>';
	if(regionID == '*') {
		for (var id in organizations) {
			var org = organizations[id];
			if(organizationID == org.id) optionsHTML += '<option value="' + org.id + '" selected="selected">' + org.name + ' (' + regions[org['regionID']] + ')</option>';
			else optionsHTML += '<option value="' + org.id + '">' + org.name + ' (' + regions[org['regionID']] + ')</option>';
		}
	}
	else {
		for (var id in organizations) {
			var org = organizations[id];
			if(org.regionID == regionID) {
				if(organizationID == org.id) optionsHTML += '<option value="' + org.id + '" selected="selected">' + org.name + ' (' + regions[org['regionID']] + ')</option>';
				else optionsHTML += '<option value="' + org.id + '">' + org.name + ' (' + regions[org['regionID']] + ')</option>';
			}
		}
	}
	selectOrgs.innerHTML = optionsHTML;
	onOrganizationChange(document.getElementById('organizationSelect'));
}

function onOrganizationChange(ctrl) {
	var organizationID = ctrl.value;
	var showExpensesBtn = document.getElementById('showExpensesBtn');
	if(organizationID == '*') {
		showExpensesBtn.disabled = true;
	}
	else {
		showExpensesBtn.disabled = false;
	}
}

function onShowExpensesClick() {
	var organizationID = document.getElementById('organizationSelect').value;
	if(organizationID == '*') {
		var showExpensesBtn = document.getElementById('showExpensesBtn');
		showExpensesBtn.disabled = true;
		return; 
	}
	
	document.location = '/organization?id='+organizationID;
}
//--></script>