<div name="scroller_placeholder"></div>

<script id="scroller_template" type="text/x-jsrender">
<span></span>
<br>layouts\scroller
<div class="panel panel-default" name="scroller_{{:descriptor.entity}}">
	<div class="panel-heading">
		{{:descriptor.header}}			
		<div class="pull-right">
			{{for descriptor.common_operations tmpl="common_operation" /}}
		</div><!-- /.pull-right -->
	</div><!-- /.panel-heading -->
	<!--<div class="panel-body"></div> /.panel-body -->
		<input hidden="" id="page" value="{{:descriptor.filter_values.page}}">
		<input hidden="" id="sort" value="{{:descriptor.filter_values.sort}}">
		<input hidden="" id="order" value="{{:descriptor.filter_values.order}}">
		<input hidden="" id="page_size" value="{{:descriptor.filter_values.page_size}}">
		
		<table class="table table-striped table-bordered table-hover table-responsive">
			<thead>
				<tr>
					{{for descriptor.columns ~filter_values = descriptor.filter_values}}
						<th>
							{{if sortable}}
								<span onclick="changeSort('{{:id}}');"><u>{{:name}}</u></span>
								{{if id === ~filter_values.sort}}
									<button type="button" class="btn btn-default btn-xs" aria-label="{{:name}}" name="{{:id}}" onclick="changeSort('{{:id}}');">
									{{if ~filter_values.order === "DESC"}}
										<span class="glyphicon glyphicon-sort-by-attributes" aria-hidden="true"></span>
									{{else}}
										<span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true"></span>
									{{/if}}
									</button>
								{{/if}}
							{{else}}
								{{:name}}
							{{/if}}
						</th>
					{{/for}}
				</tr>
			</thead>
			<tbody>
				<!-- строка фильтров -->
				<tr>
					{{for descriptor.columns ~descriptor=descriptor}}
						<td>
							{{if filter}} 
								{{if filter==="text"}} <input type="text" name="filter_{{:id}}" value="{{:filter_value}}"/>
								{{else filter==="number"}} <input type="number" name="filter_{{:id}}" value="{{:filter_value}}"/>
								{{else filter==="email"}} <input type="email" name="filter_{{:id}}" value="{{:filter_value}}"/>
								{{else filter==="list_id"}} 
									<select name="filter_{{:id}}">
										<option value="*" {{if filter_value===""}} selected="selected"{{/if}}></option>
										{{for filter_values}}
											<option value="{{:id}}" {{if id === #parent.parent.data.filter_value}} selected="selected"{{/if}}>{{:name}}</option>
										{{/for}}
									</select>
								{{else filter==="bool"}}
									<select name="filter_{{:column.id}}">
										<option value="*"/></option>
										<option value="1"/>Да</option>
										<option value="0"/>Нет</option>
									</select>
								{{/if}}
							{{else id==="operations"}}
								{{for ~descriptor.filter_operations tmpl="filter_operation" /}}
							{{/if}}
						</td>
					{{/for}}
				</tr>
				{{for items tmpl="<?php echo $controllerName; ?>_row" }}
				{{else}}	
					<!-- если данных нет -->
					<tr ><td colspan="{{:descriptor.columns.length}}"><p class="text-center"><?php echo $t->_('text_no_data'); ?></p></td></tr>
				{{/for}}
			</tbody>
		</table>
		<span class="pull-right"><?php echo $t->_('text_page_sizes'); ?>&nbsp;{{include tmpl="page_size" ~descriptor=descriptor /}}</span>
	
	<div class="panel-footer">
		{{for descriptor.pager ~descriptor=descriptor}}
			<nav>
				<ul class="pagination">
					{{if ~descriptor.filter_values.page>1}}
						<li onClick="changePage({{:~descriptor.filter_values.page}}-1);"><a href="#" aria-label="pager_prev"><span aria-hidden="true">&laquo;</span></a></li>
					{{else}}
						<li class="disabled"><span aria-label="Previous"><span aria-hidden="true">&laquo;</span></span></li>
					{{/if}}
					<!-- выводим номера страниц -->
					{{:~utilities.getPagerHtml(~descriptor)}}
					{{if ~descriptor.filter_values.page<~descriptor.pager.total_pages}}
						<li onClick="changePage({{:~descriptor.filter_values.page}}+1);"><a href="#" aria-label="pager_next"><span aria-hidden="true">&raquo;</span></a></li>
					{{else}}
						<li class="disabled"><span aria-label="Next"><span aria-hidden="true">&raquo;</span></span></li>
					{{/if}}
				</ul>
			</nav>
		{{/for}}
	</div>
</div><!-- /.panel -->
</script>

<script src="../../templates/scroller.js"></script>
<script src="../../templates/<?php echo $controllerName; ?>.js"></script>

<script type="text/javascript"><!--

$(document).ready(function() {
	apply_filter();
});

// Очищает поля фильтра, запрашивает и выводит отфильтрованные данные
function clear_filter() {
	var container = $("div [name='scroller_placeholder']");
	<?php for($i=0; $i<count($descriptor['columns']); $i++) { 
		$column = $descriptor['columns'][$i];
		if(isset($column['filter'])) {
			if($column['filter'] == 'text' || $column['filter'] == 'number' || $column['filter'] == 'email') { ?>
	container.find("input[name='filter_<?php echo $column['id']; ?>']").val("");
			<?php } else if($column['filter'] == 'list_id') { ?>
	container.find("select[name='filter_<?php echo $column['id']; ?>']").val("");
			<?php } else if($column['filter'] == 'bool') { ?>
	// TODO:
			<?php } ?>
		<?php } ?>
	<?php } ?>
}

function row_edit(entity, id){
	var url = '/'+entity+'/edit?id=' + id;
	console.log("row_edit=" + url);
	document.location = url;
}

// клик по номеру страницы
function changePage(p){
	var container = $("div [name='scroller_placeholder']");
	console.log('p='+p);
	container.find('#page').val(p);
	console.log('page='+container.find('#page').val());
	apply_filter();
}

// клик по сортировке колонки
function changeSort(id){
	var container = $("div [name='scroller_placeholder']");
	var order = container.find("#order");
	var sort = container.find("#sort");
	if(sort.val()==id) order.val() == "DESC" ? order.val("ASC") : order.val("DESC");
	else sort.val(id);
	apply_filter();
}

// выбор количества строк на странице
function changePageSize(){
	var container = $("div [name='scroller_placeholder']");
	container.find("#page_size").val(container.find("select[name='page_sizes']").val());
	apply_filter();
}

// Запрашивает и выводит отфильтрованные данные
function apply_filter() {
	url = '/<?php echo $controllerName; ?>/filter?';

	var container = $("div[name='scroller_placeholder']");
	
	var page = container.find('#page').val();
	url += 'page=' +  encodeURIComponent(page ? page : 1);
	
	var sort = container.find('#sort').val();
	if (sort) url += '&sort=' + encodeURIComponent(sort);
	
	var order = container.find('#order').val();
	if (order) url += '&order=' + encodeURIComponent(order);
	
	var page_size = container.find("select[name='page_sizes']").val();
	if (page_size) url += '&page_size=' + encodeURIComponent(page_size);
	
	<?php for($i=0; $i<count($descriptor['columns']); $i++) { 
		$column = $descriptor['columns'][$i];
		if(isset($column['filter'])) {
			if($column['filter'] == 'text' || $column['filter'] == 'number' || $column['filter'] == 'email') { ?>
	var filter_<?php echo $column['id']; ?> = container.find("input[name='filter_<?php echo $column['id']; ?>']").val();
	if (filter_<?php echo $column['id']; ?>) url += '&filter_<?php echo $column['id']; ?>=' + encodeURIComponent(filter_<?php echo $column['id']; ?>);
			<?php } else if($column['filter'] == 'list_id') { ?>
	var filter_<?php echo $column['filter_id']; ?> = container.find("select[name='filter_<?php echo $column['id']; ?>']").val();
	if (filter_<?php echo $column['filter_id']; ?> && filter_<?php echo $column['filter_id']; ?> != "*") url += '&filter_<?php echo $column['filter_id']; ?>=' + encodeURIComponent(filter_<?php echo $column['filter_id']; ?>);
			<?php } else if($column['filter'] == 'bool') { ?>
	// TODO:
			<?php } ?>
		<?php } ?>
	<?php } ?>
	
	console.log(url);
	$.ajax({
		url: url,
		dataType: 'json',
		//dataType: 'html',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			
			console.log(json);
			var tmpl = $.templates("#scroller_template");
			
			container.html(tmpl.render({descriptor:json.descriptor, items:json.items}));
		},
		error: function(xhr, ajaxOptions, thrownError) {
			//console.log(thrownError + "\r\n" + (xhr != null ? xhr.statusText + "\r\n" + xhr.responseText + "\r\n" : ""));
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			//console.log(thrownError);
			//alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
	});
}

//--></script>

