<!--<div class="row">
	<div class="col-lg-2">
		<?php echo $news['publication_date']['name']; ?>
	</div>
	<div class="col-lg-10">
		<?php echo $news['publication_date']['value']; ?>
	</div>
</div>-->
<div class="row">
	<div class="col-lg-12">
		<div class="media">
			<img class="media-object" src="" alt="">
			<div class="media-body">
				<?php echo $news['description']['value']; ?>
			</div>
		</div>
	</div>
</div>