<div class="row-fluid">
	<div class="media">
		<img class="media-object pull-left" src="<?php if($org['img']['href']!='') echo $org['img']['href']; else echo $controller->config->application->noImage; ?>" alt="" style="width:200px; height:200px;">
		<div class="media-body">
			<div class="container-fluid">
				<!--контакты-->
				<div class="row">
					<div class="col-lg-2"><p><?php echo $org['contacts']['name']; ?></p></div>
					<div class="col-lg-10"><p><?php echo $org['contacts']['value']; ?></p></div>
				</div>
				<!--email-->
				<div class="row">
					<div class="col-lg-2"><p><?php echo $org['email']['name']; ?></p></div>
					<div class="col-lg-10"><p><?php echo $org['email']['value']; ?></p></div>
				</div>
				<!--регион-->
				<div class="row">
					<div class="col-lg-2"><p><?php echo $org['region']['name']; ?></p></div>
					<div class="col-lg-10"><p><?php echo $org['region']['value']; ?></p></div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid"><p></p></div>
<div class="row-fluid">
	<button id="showExpenses" type="button" class="btn btn-primary" onclick="document.location = '/expenselist?filter_organization_id=<?php echo $org['id']['value']; ?>'">Перейти к расходам</button>
	<button id="organizationRequest" type="button" class="btn btn-default" onclick="organizationRequest(<?php echo $org["id"]["value"]; ?>);">Задать вопрос</button>
</div>
<div class="row-fliud">
	<!-- Chart -->
	<div id="myPieChart" style="width: 100%; height: 728px;"/>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript"><!--

var descriptor = {
	columns: [
		{type: 'string', value: 'Тип расхода'},
		{type: 'number', value: 'Сумма, тыс. р.'},
		{type: 'number', value: 'Средний расход, тыс. р.'},
		{type: 'number', value: 'Идентификатор'}
	],
	rows: [
		<?php if(isset($expenseTypes)) { 
			foreach($expenseTypes as $id => $type) { ?>
				['<?php echo $type['name']; ?>', <?php echo $type['sum']; ?>, <?php echo $type['prcnt']; ?>, <?php echo $id; ?>],
			<?php } ?>
		<?php } ?>
	]
}
google.charts.load('current', {packages: ['corechart']});
google.charts.setOnLoadCallback(drawChart);

function drawChart() {
	if(descriptor.rows.length>0) {
		// Define the chart to be drawn.
		var data = new google.visualization.DataTable();
		var len = descriptor.columns.length;
		for(var i = 0; i < len; i++) data.addColumn(descriptor.columns[i].type, descriptor.columns[i].value);
		data.addRows(descriptor.rows);
		
		var formatter = new google.visualization.NumberFormat({
			fractionDigits: 0,
			groupingSymbol: ' ',
			suffix: ' тыс. р.',
			//pattern: '###############',
		});
		formatter.format(data, 1);
		formatter.format(data, 2);
		
		var options = {
			title: '<?php echo str_replace("{year}", $year, $controller->t->_("text_organization_chart_title")); ?>',
			//pieHole: 0.4 // You can't combine the pieHole and is3D options; if you do, pieHole will be ignored.
			//is3D: true,
		};
		
		var chart = new google.visualization.PieChart(document.getElementById('myPieChart'));
		// The select handler. Call the chart's getSelection() method
		function selectHandler(e) {
			var selectedItem = chart.getSelection()[0];
			if (selectedItem) {
				var rowID = selectedItem.row
				var row = descriptor.rows[rowID];
				var value = row[0] + ' = ' + row[1];
				//alert('Выбрано: ' + value);
				console.log('Выбрано: ' + value);
				var url = '/expenselist?filter_expense_type_id=' + row[3] + '&' + 'filter_organization_id=<?php echo $org['id']['value']; ?>';
				document.location = url;
				
				console.log('document.location = ' + url);
			}
		}

		// Listen for the 'select' event, and call my function selectHandler() when
		// the user selects something on the chart.
		google.visualization.events.addListener(chart, 'select', selectHandler);

		// Instantiate and draw the chart.
		chart.draw(data, options);
	}
}
//--></script>