<div class="row-fluid">
	<div class="media">
		<img class="media-object pull-left" src="<?php if($org['img']['href']!='') echo $org['img']['href']; else echo $controller->config->application->noImage; ?>" alt="" style="width:200px; height:200px;">
		<div class="media-body">
			<div class="container-fluid">
				<!--контакты-->
				<div class="row">
					<div class="col-lg-2"><p><?php echo $org['contacts']['name']; ?></p></div>
					<div class="col-lg-10"><p><?php echo $org['contacts']['value']; ?></p></div>
				</div>
				<!--email-->
				<div class="row">
					<div class="col-lg-2"><p><?php echo $org['email']['name']; ?></p></div>
					<div class="col-lg-10"><p><?php echo $org['email']['value']; ?></p></div>
				</div>
				<!--регион-->
				<div class="row">
					<div class="col-lg-2"><p><?php echo $org['region']['name']; ?></p></div>
					<div class="col-lg-10"><p><?php echo $org['region']['value']; ?></p></div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid"><div class="col-lg-12"><p></p></div></div>
<div class="row-fluid"><div class="col-lg-12">
	<button id="showExpenses" type="button" class="btn btn-primary" onclick="document.location = '/expenselist?filter_organization=<?php echo $org['id']['value']; ?>'">Перейти к расходам</button>
	<!--<button id="organizationRequest" type="button" class="btn btn-default" onclick="organizationRequest2(<?php //echo $org["id"]["value"]; ?>);">Задать вопрос</button>-->
</div></div>

<?php $select = '<select id="filter_year" onchange="onYearChange(this);">'; 
	$count = count($expenses["years"]); 
	for($i=0; $i<$count; $i++) { 
		$select .= '<option value="' . $expenses["years"][$i] . '"' . (($expenses["years"][$i] == $expenses["year"]) ? ' selected="selected"' : '') . '>' . $expenses["years"][$i] . '</option>'; 
	} 
	$select .= '</select>'; 
?>

<div class="row-fliud">
	<div class="col-lg-12 text-center">
		<h3><?php echo str_replace("{year}", $select, $controller->t->_("text_organization_chart_title")); ?></h3>
		<div class="row-fliud<?php if(isset($expenses["totalSum"]) && 0 < $expenses["totalSum"]) { ?> hidden<?php } ?>" id="chartNoDataHeader" >
			<div class="col-lg-12 text-center"><?php echo $controller->t->_("text_organization_chart_no_data"); ?></div>
		</div>
	</div>
</div>

<div class="row-fliud"><div class="col-lg-12">
	<!-- Chart -->
	<div id="myPieChart" style="width:800px; height:400px;"/>
</div></div>

<?php //var_dump($expenses); ?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript"><!--

function onYearChange(ctrl) {
	year = ctrl.value;
	var url = '/<?php echo $controllerName; ?>/filter?id=<?php echo $org["id"]["value"]; ?>&filter_year=' + year;
	console.log(url);
	$.ajax({
		url: url,
		dataType: 'json',
		//dataType: 'html',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: (function(json) {
			if(!handleAjaxError(json.error)) {
				// используется замкание и bind, в свойстве this хранится container скроллера, как контекст
				console.log(json);
				descriptor.rows = [];
				if(json.totalSum && json.totalSum>0){
					$('#chartNoDataHeader').hide();
					for (var key in json.expenseTypes) {
						type = json.expenseTypes[key];
						descriptor.rows.push([type.name, Number(type.sum), Number(type.prcnt), parseInt(key)]);
					}
					//chart.clearChart();
					//google.charts.load('current', {packages: ['corechart']});
					drawChart();
				}
				else {
					$('#chartNoDataHeader').show();
					chart.clearChart();
				}
			}
		}),
		error: function(xhr, ajaxOptions, thrownError) {
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			handleAjaxError({
				messages: [{
					title: 'Ошибка обмена данными',
					msg: 'Ошибка обработки запроса на стороне сервера. Обратитесь в службу поддержки',
				}],
			});
		}
	});
}


var descriptor = {
	columns: [
		{type: 'string', value: '<?php echo $t->_('text_organization_chart_expensetype_name'); ?>'},
		{type: 'number', value: '<?php echo $t->_('text_entity_property_amount'); ?>'},
		{type: 'number', value: '<?php echo $t->_('text_organization_chart_expensetype_percent'); ?>'},
		{type: 'number', value: '<?php echo $t->_('text_organization_chart_id'); ?>'}
	],
	rows: [
		<?php if(isset($expenses["expenseTypes"])) { 
			foreach($expenses["expenseTypes"] as $id => $type) { ?>
				['<?php echo $type['name']; ?>', <?php echo $type['sum']; ?>, <?php echo $type['prcnt']; ?>, <?php echo $id; ?>],
			<?php } ?>
		<?php } ?>
	]
}
google.charts.load('current', {packages: ['corechart']});
google.charts.setOnLoadCallback(drawChart);
var chart = null;
var year = <?php echo $expenses["year"]; ?>

function drawChart() {
	document.getElementById('filter_year').value = year;
	if(descriptor.rows.length>0) {
		// Define the chart to be drawn.
		var data = new google.visualization.DataTable();
		var len = descriptor.columns.length;
		for(var i = 0; i < len; i++) data.addColumn(descriptor.columns[i].type, descriptor.columns[i].value);
		data.addRows(descriptor.rows);
		
		var formatter = new google.visualization.NumberFormat({
			fractionDigits: 0,
			groupingSymbol: ' ',
			suffix: app.t._('currency_thousand_short'),
			//pattern: '###############',
		});
		formatter.format(data, 1);
		formatter = new google.visualization.NumberFormat({
			fractionDigits: 2,
			groupingSymbol: ' ',
			suffix: ' %',
			//pattern: '###############',
		});
		formatter.format(data, 2);
		
		var options = {
			//pieHole: 0.4 // You can't combine the pieHole and is3D options; if you do, pieHole will be ignored.
			//is3D: true,
			//backgroundColor: 'blue',
			width: '800px',
			height: '400px',
			chartArea: {top:'20px', width: "100%", height: "100%"},
			legend: {
				position: 'right', 
				//position: 'top', 
				alignment: 'center',
				//alignment: 'start',
				//maxLines: 16,
				textStyle: {fontSize: 14},
			},
		};
		
		//if(chart!=null) chart.clearChart();
		chart = new google.visualization.PieChart(document.getElementById('myPieChart'));
		// The select handler. Call the chart's getSelection() method
		function selectHandler(e) {
			var selectedItem = chart.getSelection()[0];
			if (selectedItem) {
				var rowID = selectedItem.row
				var row = descriptor.rows[rowID];
				var value = row[0] + ' = ' + row[1];
				//alert('Выбрано: ' + value);
				console.log('Выбрано: ' + value);
				var url = '/expenselist?filter_expense_type=' + row[3] + '&' + 'filter_organization=<?php echo $org['id']['value']; ?>&filter_target_date=' + year;
				document.location = url;
				
				console.log('document.location = ' + url);
			}
		}

		// Listen for the 'select' event, and call my function selectHandler() when
		// the user selects something on the chart.
		google.visualization.events.addListener(chart, 'select', selectHandler);

		// Instantiate and draw the chart.
		chart.draw(data, options);
	}
}
//--></script>