<div class="container">
	<div class="row">
		<div class="col-lg-4"></div>
		<div class="col-lg-4">
			<form class="form-signin">
				<h2 class="form-signin-heading text-center">Авторизация</h2>
				<div class="input-group">
					<span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
					<input type="email" id="email" class="form-control" placeholder="Email" autofocus="">
				</div>
				<div class="row"><div class="col-lg-12 text-center">ИЛИ</div></div>
				<div class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-phone-alt"></i></span>
						<input id="phone" type="tel" class="form-control" name="phone" value="" placeholder="Телефон" pattern="[0-9]+" maxlength="12">                                        
				</div>
				<div class="row"><div class="col-lg-12 text-center">&nbsp;</div></div>
				<div class="input-group">
						<span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
						<input id="password" type="password" class="form-control" name="password" value="" required="" placeholder="Пароль">                                        
				</div>
				<div class="checkbox">
					<label>
						<input type="checkbox" value="remember-me"> Запомнить меня
					</label>
				</div>
				<!--<button class="btn btn-lg btn-primary btn-block" type="submit" onclick="login();" formmethod="post" formaction="/session/start">Войти</button>-->
				<button class="btn btn-lg btn-primary btn-block" onclick="login();">Войти</button>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript"><!--

function login() {
	var url = '/session/start?';
	//var modal = $("#logonModal");
	var modal = $(".form-signin");
	
	var phone = modal.find('#phone').val();
	if (phone) url += '&phone=' + encodeURIComponent(phone);
	var email = modal.find('#email').val();
	if (email) url += '&email=' + encodeURIComponent(email);
	var password = modal.find('#password').val();
	password = sha1(password);
	if (password) url += '&password=' + encodeURIComponent(password);
	
	console.log(url);
	
	$.ajax({
		url: url,
		dataType: 'json',
		method: 'get',
		beforeSend: function() {
				// показываем прогрессбар
		},
		complete: function() {
			// скрываем прогрессбар
		},			
		success: function(json) {
			if(!handleAjaxError(json.error)) {
				if(json.success.redirect) document.location = json.success.redirect;
			}
			
		},
		error: function(xhr, ajaxOptions, thrownError) {
			//console.log(thrownError + "\r\n" + (xhr != null ? xhr.statusText + "\r\n" + xhr.responseText + "\r\n" : ""));
			console.log(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
			//console.log(thrownError);
			//alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
	});
}


//--></script>

