<?php
$messages = array(
// Locale
"code"                  => "ru",
"date_format_short"     => "d.m.Y",
"date_format_long"      => "l dS F Y",
"time_format"           => "h:i:s A",
"decimal_point"         => ".",
"thousand_point"        => " ",
"currency_short"        => "р",

// Text
"text_home"             => "Главная",
"text_yes"              => "Да",
"text_no"               => "Нет",
"text_none"             => " --- Не выбрано --- ",
"text_select"           => " --- Выберите --- ",
"text_pagination"       => "Показано с {start} по {end} из {total} (страниц: {pages})",
"text_page_sizes"       => "Показывать по",
"text_separator"        => " &raquo; ",
"text_search"    				=> "Поиск",
"text_active_short"    	=> "(акт.)",
"text_nonactive_short"  => " (неакт.)",
"text_site_full_name"		=> "Интернет портал общедоступной информации о расходах муниципальных образований «Расходы города»",
"text_site_short_name"		=> "Расходы города",

// Tabs
"text_tab_main_information" => "Основная информация",
"text_tab_properties" => "Свойства",
"text_tab_geodata" => "Геоинформация",

// Common entities properties labels
"text_entity_property_actions" => "Действия",
"text_entity_property_active" => "Активность",
"text_entity_property_amount" => "Сумма, р.",
"text_entity_property_code" => "Код",
"text_entity_property_contacts" => "Контакты",
"text_entity_property_coordinates_x" => "X = ",
"text_entity_property_coordinates_y" => "Y = ",
"text_entity_property_created_at" => "Создано",
"text_entity_property_created_by" => "Автор",
"text_entity_property_date" => "Дата",
"text_entity_property_description" => "Описание",
"text_entity_property_email" => "Email",
"text_entity_property_files" => "Файлы",
"text_entity_property_fio" => "ФИО",
"text_entity_property_header" => "Заголовок",
"text_entity_property_id" => "ID",
"text_entity_property_image" => "Изображение",
"text_entity_property_images" => "Изображения",
"text_entity_property_login" => "Логин",
"text_entity_property_n" => "№",
"text_entity_property_name" => "Наименование",
"text_entity_property_password" => "Пароль",
"text_entity_property_phone" => "Телефон",
"text_entity_property_recipient" => "Получатель",
"text_entity_property_region" => "Регион",
"text_entity_property_related_data" => "Связанные записи",
"text_entity_property_role" => "Роль",
"text_entity_property_status" => "Статус",
"text_entity_property_value" => "Значение",

// Statuses
"status_new" => "Новый",
"status_prcessed" => "Обработано",
"status_declined" => "Отказано",
"status_in_progress" => "В обработке",

// Buttons
"button_add_address"    => "Добавить адрес",
"button_add"			=> "Добавить",
"button_back"			=> "Назад",
"button_save"			=> "Сохранить",
"button_save_direct"	=> "Сохранить на сервер",
"button_save_local"		=> "Сохранить локально",
"button_select"			=> "Указать",
"button_continue"       => "Продолжить",
"button_wishlist"       => "в закладки",
"button_confirm"        => "Подтвердить",
"button_coupon"         => "Применить купон",
"button_delete"         => "Удалить",
"button_download"       => "Скачать",
"button_edit"           => "Редактировать",
"button_copy"           => "Копировать",
"button_apply"          => "Применить",
"button_clear"          => "Очистить",
"button_filter"         => "Фильтровать",
"button_filter_clear"   => "Сброс",
"button_new_address"    => "Новый адрес",
"button_change_address" => "Изменить адрес",
"button_login"          => "Войти",
"button_update"         => "Применить",
"button_remove"         => "Удалить",
"button_search"         => "Поиск",
"button_view"           => "Просмотр",
"button_upload"         => "Загрузить",

// Information
"text_no_data"        => "Нет данных для отображения",
"text_no_edit"        => "Редактирование невозможно",

// Error
"error_upload_1"        => "Загружаемый на сервер файл превышает параметр upload_max_filesize в php.ini!",
"error_upload_2"        => "Загружаемый на сервер файл превышает параметр MAX_FILE_SIZE который определен в HTML форме!",
"error_upload_3"        => "Загружаемый на сервер файл был загружен не полностью!",
"error_upload_4"        => "Файл не был загружен!",
"error_upload_6"        => "Отсутсвует временная директория!",
"error_upload_7"        => "Не удалось записать файл на диск!",
"error_upload_8"        => "Загружаемый на сервер файл не подходит по расширению!",
"error_upload_999"      => "Неизвестная ошибка!"
);
