<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<meta name="description" content="<?php echo $controller->t->_("text_site_short_name"); ?>"/>
		<meta name="author" content="Porgibnoy"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<!-- для соцсетей 
		<meta property="og:image" content="http://<?php //echo $controller->config->application->host;?>/img/logo.png" />
		<meta property="og:title" content="Новость!" />
		<meta property="og:description" content="Опросы на сайте <?php //echo $controller->config->application->host;?>" />-->
		
		<!--<title>##Наименование сайта</title>-->
		
		<link rel="shortcut icon" type="image/png" href="/favicon.png"/>
		<!--<link rel="shortcut icon" type="image/png" href="<?php //echo $controller->config->application->commonHost; ?>/favicon.png"/>-->
		
		<link rel="stylesheet" type="text/css" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"/>
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"/>	
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css">
		<link rel="stylesheet" type="text/css" media="all" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.9/select2-bootstrap.min.css">
		
    </head>
    <body>
		<div class="container">
			<?php echo $this->getContent(); ?>
			
			<div class="row text-center">
				<div class="col-lg-12">
					<hr>
					<a href="/"><?php echo $controller->t->_("text_site_short_name"); ?></a> &copy; 2016. Все права защищены.<br />Версия 0.2
				</div>
			</div>
		</div>
    		<!-- jquery: везде -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-json/2.6.0/jquery.json.min.js"></script>
		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.5/bootstrap-notify.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.82/jsrender.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/js-sha1/0.3.0/sha1.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/ru.js"></script>
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
		
		<script src="<?php echo $controller->config->application->commonHost; ?>/public/common.js"></script>
		<!-- для работы с модальными окнами  -->
		<script type="text/javascript" src="<?php echo $controller->config->application->commonHost; ?>/public/modal.js"></script>
		<script type="text/javascript" src="http://<?php echo $controller->config->application->host; ?>/public/common-client.js"></script>
		<script src="<?php echo $controller->config->application->commonHost; ?>/public/templates/common_templates.js"></script>
		<script src="<?php echo $controller->config->application->commonHost; ?>/public/templates/scroller.js"></script>
		<script src="<?php echo $controller->config->application->commonHost; ?>/public/templates/entity.js"></script>
		<?php 
			$this->partial(APP_PATH . $this->config->application->commonTemplatesDir . "form_template");
			$this->partial(APP_PATH . $this->config->application->commonTemplatesDir . "scroller_template"); 
		?>
	</body>
</html>